// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwrigznwfbkxiycedyds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cmlnem53ZmJreGl5Y2VkeWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDE0MzEsImV4cCI6MjA2NTIxNzQzMX0.yq5JKshusK3-OtgxOVB7c0QEjDfQ5T175eS78xajf7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);